export const contentEs = {
  nav: {
    explore: "Explorar causas",
    closed: "Cerradas",
    finalized: "Finalizadas",
    howItWorks: "Cómo funciona",
    createCause: "Crear una causa",
    createCauseShort: "Crear causa",
    signIn: "Entrar",
    saved: "Guardadas",
    profile: "Perfil",
    settings: "Ajustes",
    signOut: "Cerrar sesión",
    more: "Más",
  },
  hero: {
    title: "Cada luz es una persona que necesita ayuda.",
    subtitle: "Gira el planeta y toca un país para conocer a quién puedes apoyar ahí, sin intermediarios.",
    searchPlaceholder: "Busca un país, ciudad o persona",
    statusSuffix: "causas activas en",
    countriesSuffix: "países",
    recentActivity: "Actividad reciente",
    emptyCountry: "Todavía no hay causas activas aquí.",
    emptyCountryCta: "Si tú o alguien cercano necesita apoyo en {country}, crea la primera causa y aparecerá una luz en el mapa.",
    viewAllInCountry: "Ver las {count} causas de {country}",
    viewSingleInCountry: "Ver la causa de {country}",
  },
  feed: {
    allCountries: "Todos los países",
    allCategories: "Todas las categorías",
    followingOnly: "Siguiendo",
    donate: "Donar",
    share: "Compartir",
    save: "Guardar",
    saved: "Guardada",
    comment: "Comentar",
    comments: "comentarios",
    viewComments: "Ver los {count} comentarios",
    reportedOf: "reportados de",
    emptyActive: "No hay causas activas en este momento con estos filtros.",
    endOfFeed: "Ya viste todas las causas activas.",
    loadMoreError: "No pudimos cargar más causas.",
    retry: "Reintentar",
  },
  howItWorks: {
    step1Title: "Publica tu causa",
    step1Desc: "Cuenta qué pasó, sube al menos dos fotos, indica tu ciudad y los medios por donde puedes recibir donaciones.",
    step2Title: "Recibe apoyo directo",
    step2Desc: "Quienes quieran ayudarte te envían el dinero directamente a tus medios. Puente no recibe, no retiene y no cobra comisión sobre ninguna donación.",
    step3Title: "Cierra y muestra resultados",
    step3Desc: "Cuando termines, cierra tu causa y comparte fotos del antes y el después para que quienes te apoyaron vean lo que lograron juntos.",
  },
  cause: {
    statusActive: "Activa",
    statusClosed: "Cerrada",
    statusFinalized: "Finalizada",
    howToDonate: "Cómo donar",
    mustSignInToDonate: "Inicia sesión para ver cómo donar",
    noLongerAccepting: "Esta causa ya no recibe donaciones",
    copyData: "Copiar",
    copied: "¡Copiado!",
    publishedAt: "Publicada {time}",
    closedAt: "Cerrada {time}",
    finalizedAt: "Finalizada {time}",
    resultsTitle: "Resultados",
    beforeAfter: "Antes y después",
    resultsSummary: "Resumen de resultados",
    amountReceived: "Monto recibido",
    closeCause: "Cerrar causa",
    publishResults: "Publicar resultados",
    editCause: "Editar causa",
    waitingResults: "Esperando resultados",
  },
};

export type FeedPanelKey = "explorar" | "cerradas" | "finalizadas";

export const feedPanelsConfig = {
  explorar: {
    status: "activa" as const,
    title: "Causas activas",
    countText: (n: number) => (n === 1 ? "1 causa activa" : `${n} causas activas`),
    searchPlaceholder: "Busca por causa, ciudad o persona",
    emptyNoFiltersTitle: "Todavía no hay causas activas.",
    emptyNoFiltersAction: { text: "Crear una causa", href: "/causa/nueva" },
    emptyWithFiltersTitle: "No encontramos causas activas con estos filtros.",
    emptyWithFiltersAction: "Limpiar filtros",
  },
  cerradas: {
    status: "cerrada" as const,
    title: "Causas cerradas",
    countText: (n: number) => (n === 1 ? "1 causa cerrada" : `${n} causas cerradas`),
    searchPlaceholder: "Busca entre las causas cerradas",
    emptyNoFiltersTitle: "Aún no hay causas cerradas.",
    emptyNoFiltersAction: { text: "Ver causas activas", href: "/explorar" },
    emptyWithFiltersTitle: "No encontramos causas cerradas con estos filtros.",
    emptyWithFiltersAction: "Limpiar filtros",
  },
  finalizadas: {
    status: "finalizada" as const,
    title: "Causas finalizadas",
    countText: (n: number) => (n === 1 ? "1 causa con resultados" : `${n} causas con resultados`),
    searchPlaceholder: "Busca entre los resultados",
    emptyNoFiltersTitle: "Aún nadie ha publicado resultados.",
    emptyNoFiltersAction: { text: "Ver causas cerradas", href: "/cerradas" },
    emptyWithFiltersTitle: "No encontramos resultados con estos filtros.",
    emptyWithFiltersAction: "Limpiar filtros",
  },
};

